AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    Handler: index.handler
    Architecture: arm
    Memory: 128
    Runtime: python3.9

Resources:
  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Junior-Food
      Description: A simple food deliver app

Outputs:
  HelloEfsApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
